#!/bin/bash
echo -e "\e[7mWhat would you like to name your new share?\e[27m"
read sharename
echo >> /etc/samba/smb.conf
echo [$sharename] >> /etc/samba/smb.conf
echo -e "\e[7mWhich directory should this share lead to? (Full path)\e[27m"
read sharepath
echo path = $sharepath >> /etc/samba/smb.conf
echo "read only = no" >> /etc/samba/smb.conf
echo "guest ok = no" >> /etc/samba/smb.conf
echo "browseable = yes" >> /etc/samba/smb.conf
echo -e "\e[7mWhich users should be allowed to access this share? (Separate with spaces)\e[27m"
read validusers
echo valid users = $validusers >> /etc/samba/smb.conf
echo "spotlight = yes" >> /etc/samba/smb.conf
echo "vfs objects = catia fruit streams_xattr" >> /etc/samba/smb.conf
echo "fruit:aapl = yes" >> /etc/samba/smb.conf
echo "fruit:time machine = yes" >> /etc/samba/smb.conf
echo -e "\e[7mCongratulations! You now have a working Apple and Time Machine Samba share!\e[27m"
sudo service smbd restart