#!/bin/bash
sudo apt install samba -y
sudo mv /etc/samba/smb.conf /etc/samba/smb.conf.bak
echo "What would you like to name your share?"
read sharename
echo >> smb.conf
echo [$sharename] >> smb.conf
echo "Which directory should this share lead to? (Full path)"
read sharepath
echo path = $sharepath >> smb.conf
echo "read only = no" >> smb.conf
echo "guest ok = no" >> smb.conf
echo "browseable = yes" >> smb.conf
echo "Which users should be allowed to access this share? (Separate with spaces)"
read validusers
echo valid users = $validusers >> smb.conf
echo "spotlight = yes" >> smb.conf
echo "vfs objects = catia fruit streams_xattr" >> smb.conf
echo "fruit:aapl = yes" >> smb.conf
echo "fruit:time machine = yes" >> smb.conf
echo "Congratulations! You now have a working Apple and Time Machine Samba share!"
sudo mv smb.conf /etc/samba/
sudo service smbd restart