#!/bin/bash
echo -e "\e[7mWhat would you like to name your new share?\e[27m"
read sharename
echo >> /etc/samba/smb.conf
echo [$sharename] >> /etc/samba/smb.conf
echo -e "\e[7mWhich directory should this share lead to? (Full path)\e[27m"
read sharepath
echo path = $sharepath >> /etc/samba/smb.conf
echo "read only = no" >> /etc/samba/smb.conf
echo "guest ok = no" >> /etc/samba/smb.conf
echo "browseable = yes" >> /etc/samba/smb.conf
echo -e "\e[7mWhich users should be allowed to access this share? (Separate with spaces and for groups use the format @groupname)\e[27m"
read validusers
echo valid users = $validusers >> /etc/samba/smb.conf
echo "spotlight = yes" >> /etc/samba/smb.conf
echo "vfs objects = catia fruit streams_xattr" >> /etc/samba/smb.conf
echo "fruit:aapl = yes" >> /etc/samba/smb.conf
echo -e "\e[7mWould you like the share to show up as a Time Machine drive? (y/n)\e[27m"
read timemachine
if [ $timemachine == "y" ]
then
    echo "fruit:time machine = yes" >> smb.conf
    echo "\e[7mTime Machine support will be added.\e[27m"
else
    echo "\e[7mTime Machine support WILL NOT be added.\e[27m"
fi
echo -e "\e[7mCongratulations! You now have a working Apple and Time Machine Samba share!\e[27m"
sudo service smbd restart
